### PR TITLE
Auth SDK new readme content for beta

### PR DESCRIPTION
**Pull request by shaloo**
Saved as DOCS.md for now, will be switched to README.md at beta.

Note:  The banner and logo are placeholders. Similar to license file, I will have those picked up from one source of truth.

### CODE REVIEW

**Comment by makylfang** [comment]
Header image has a missing space.

**Comment by shaloo** [comment]
> 

Do you mean the LHS black area space inside the image?  Don't worry about it - it is a placeholder image I pulled out (screenshot) from 'part' of one of the Figma prototypes.  Its content is not even related much to Auth.  I am hoping to replace it with a true Arcana banner image once the Design team offers something for it. Ditto for wallet and storage READMEs.

**Comment by makylfang** [comment]
@shaloo No I mean the space between developers and to in the line `It is our mission to make it easy for developersto ensure the security and privacy of user data` but I guess its just a placeholder.

**Comment by shaloo** [comment]
> 

Yes, that is correct. I'll just use a better placeholder image for now to avoid any confusion.

**Comment by shaloo** [comment]
I do not want to issue unnecessary notifications while I clean this up, hence closing. Will create a fresh PR after I am done. Thanks.

**Pull request closed without merging**
